ALTER TABLE "negocio" ADD COLUMN IF NOT EXISTS "email_contacto" VARCHAR(200);
ALTER TABLE "negocio" ADD COLUMN IF NOT EXISTS "telefono" VARCHAR(30);
ALTER TABLE "negocio" ADD COLUMN IF NOT EXISTS "direccion" VARCHAR(300);
